# fly.toml app configuration file generated for server-minto-1711 on 2025-10-20T13:21:07+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-minto-1711'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 4999
  force_https = true
  auto_stop_machines = false  # Sửa thành false để không tự động dừng máy
  auto_start_machines = true
  min_machines_running = 1    # Đảm bảo ít nhất 1 máy luôn chạy
  processes = ['app']
  [http_service.concurrency]
    type = "requests"
    soft_limit = 20
    hard_limit = 25

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1